---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(RSQLite)
```

```{r}
fn <- "pubmed_sample.xml"
dbfn <- "pubmed.db"
```

```{r, include=FALSE}
DBcon <- dbConnect(RSQLite::SQLite(), dbfn)
dbExecute(DBcon, "PRAGMA foreign_keys = ON")
```

Drop tables
```{sql connection = "DBcon"}
drop table if exists articlePub;
```

```{sql connection = "DBcon"}
drop table if exists dimTime;
```

```{sql connection = "DBcon"}
drop table if exists dimJournalIssue;
```

```{sql connection = "DBcon"}
drop table if exists dimJournal;
```

```{sql connection = "DBcon"}
drop table if exists dimArticle;
```

```{sql connection = "DBcon"}
drop table if exists dimAuthorList;
```

```{sql connection = "DBcon"}
drop table if exists Author;
```

Create tables
```{sql connection = "DBcon"}
CREATE TABLE articlePub (
  PMID INTEGER,
  ISSN TEXT,
  tid INTEGER AUTO_INCREMENT,
  aggregate INTEGER,
  PRIMARY KEY (PMID, ISSN, tid),
  FOREIGN KEY (PMID) REFERENCES dimArticle(PMID),
  FOREIGN KEY (ISSN) REFERENCES dimJournal(ISSN),
  FOREIGN KEY (tid) REFERENCES dimTime(tid),
);
```


```{sql connection = "DBcon"}
CREATE TABLE dimTime (
  tid INTEGER PRIMARY KEY,
  Year INTEGER,
  Month TEXT,
  Quarter TEXT
);
```

```{sql connection = "DBcon"}
CREATE TABLE dimJournal (
  ISSN TEXT PRIMARY KEY,
  Title TEXT,
  ISOabbreviation TEXT
);
```

```{sql connection = "DBcon"}
CREATE TABLE dimArticle (
  PMID INTEGER PRIMARY KEY,
  ArticleTitle TEXT,
  ArticleDate DATE,
  Language TEXT,
  AuthorList_id INTEGER AUTO_INCREMENT,
  FOREIGN KEY (AuthorList_id) REFERENCES dimAuthorList(AuthorList_id)
);
```

```{sql connection = "DBcon"}
CREATE TABLE dimAuthorList (
  AuthorList_id INTEGER PRIMARY KEY,
  Author_id INTEGER,
  FOREIGN KEY (Author_id) REFERENCES ON dimAuthor(Author_id)
);
```

```{sql connection = "DBcon"}
CREATE TABLE author (
  Author_id INTEGER PRIMARY KEY,
  LastName TEXT,
  ForeName TEXT,
  Initial TEXT,
  Affiliation TEXT
);
```

Insert data
```{sql connection = "DBcon"}
INSERT INTO articlePub(PMID, ISSN)
SELECT Article.PMID, Journal.ISSN
FROM Article NATURAL JOIN Journal
```

```{sql connection = "DBcon"}
INSERT INTO dimTime(tid, Year, Month, Quarter)
SELECT articlePub.tid, Journal.Year, Journal.Month, ((Journal.Month - 1) div 3) + 1
FROM articlePub LEFT JOIN Article
ON articlePub.PMID = Article.PMID
LEFT JOIN Journal
ON Article.j_id = Journal.j_id
```

```{sql connection = "DBcon"}
INSERT INTO dimJournal(ISSN, Title, ISOabbreviation)
SELECT DISTINCT ISSN, Title, ISOabbreviation
FROM Journal
```

```{sql connection = "DBcon"}
INSERT INTO dimArticle
SELECT PMID, ArticleTitle, ArticleDate, Language
FROM Article
```

```{sql connection = "DBcon"}
INSERT INTO dimArticle
SELECT PMID, ArticleTitle, ArticleDate, Language
FROM Article
```

```{sql connection = "DBcon"}
INSERT INTO dimAuthorList
SELECT dimArticle.AuthorList_id, Author.Author_id
FROM dimArticle LEFT JOIN Author
ON dimArticle.PMID = Author.PMID
```

```{sql connection = "DBcon"}
INSERT INTO author
SELECT Author_id, LastName, ForeName, Initial, Affiliation
FROM Author
```

```{sql connection = "DBcon"}
INSERT INTO articlePub(aggregate)
SELECT COUNT(*) aggregate
FROM Article NATURAL JOIN Journal
LEFT JOIN Author
ON Article.PMID = Author.PMID
LEFT JOIN dimTime
ON dimTime.tid = article.tid
GROUP BY Author.ForeName, Journal.Title, Journal.Year, dimTime.Quarter
```