---
title: "R Notebook"
output: html_notebook
---

---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(RSQLite)
```

```{r}
fn <- "pubmed_sample.xml"
dbfn <- "pubmed.db"
```

```{r, include=FALSE}
DBcon <- dbConnect(RSQLite::SQLite(), dbfn)
dbExecute(DBcon, "PRAGMA foreign_keys = ON")
```

Drop tables

```{sql connection = "DBcon"}
drop table if exists articleFact;
```

```{sql connection = "DBcon"}
drop table if exists dimTime;
```

```{sql connection = "DBcon"}
drop table if exists dimJournal;
```

```{sql connection = "DBcon"}
drop table if exists dimArticle;
```

```{sql connection = "DBcon"}
drop table if exists dimAuthor;
```

Create tables

```{sql connection = "DBcon"}
CREATE TABLE articleFact (
  PMID INTEGER,
  Author_id INTEGER,
  ISSN TEXT,
  tid INTEGER AUTO_INCREMENT,
  PRIMARY KEY (PMID, Author_id),
  FOREIGN KEY (PMID) REFERENCES dimArticle(PMID),
  FOREIGN KEY (ISSN) REFERENCES dimJournal(ISSN),
  FOREIGN KEY (tid) REFERENCES dimTime(tid)
);
```

```{sql connection = "DBcon"}
CREATE TABLE dimTime (
  tid INTEGER PRIMARY KEY,
  Year INTEGER,
  Month TEXT
);
```

```{sql connection = "DBcon"}
CREATE TABLE dimJournal (
  ISSN TEXT PRIMARY KEY,
  Title TEXT,
  ISOabbreviation TEXT,
  CitedMedium TEXT
);
```

```{sql connection = "DBcon"}
CREATE TABLE dimArticle (
  PMID INTEGER PRIMARY KEY,
  ArticleTitle TEXT,
  ArticleDate DATE,
  Language TEXT
);
```

```{sql connection = "DBcon"}
CREATE TABLE dimAuthor (
  Author_id INTEGER PRIMARY KEY,
  LastName TEXT,
  ForeName TEXT,
  Initial TEXT,
  Affiliation TEXT
);
```

# Insert Data

```{sql connection = "DBcon"}
INSERT INTO articleFact(PMID, Author_id, ISSN)
SELECT Article.PMID, Author_ref.Author_id, Journal.ISSN
FROM Author_ref LEFT JOIN Article
ON Article.PMID == Author_ref.PMID
LEFT JOIN Journal
ON Article.j_id = Journal.j_id
```

```{sql connection = "DBcon"}
INSERT INTO dimJournal(ISSN, Title, ISOabbreviation, CitedMedium)
SELECT ISSN, Title, ISOabbreviation, CitedMedium
FROM Journal
```

```{sql connection = "DBcon"}
INSERT INTO dimTime(tid, Year, Month)
SELECT articleFact.tid, Journal.Year, Journal.Month
FROM articleFact LEFT JOIN Article
ON articleFact.PMID = Article.PMID
LEFT JOIN Journal
ON Article.j_id = Journal.j_id
```

```{sql connection = "DBcon"}
INSERT INTO dimArticle(PMID, ArticleTitle, ArticleDate, Language)
SELECT PMID, ArticleTitle, ArticleDate, Language
FROM Article
```

```{sql connection = "DBcon"}
INSERT INTO dimAuthor(Author_id, LastName, ForeName, Initial, Affiliation)
SELECT Author_id, LastName, FoerName, Initial, Affiliation
FROM Author
```


#Summary Table

```{sql connection = "DBcon"}
drop table if exists articleSummary;
```

```{sql connection = "DBcon"}
CREATE TABLE articleSummary (
  PMID INTEGER,
  Author_id INTEGER,
  ISSN TEXT,
  Year INTEGER,
  Quarter INTEGER,
  Month INTEGER,
  subtotal INTEGER,
  PRIMARY KEY (PMID, Author_id),
  FOREIGN KEY (PMID) REFERENCES dimArticle(PMID),
  FOREIGN KEY (ISSN) REFERENCES dimJournal(ISSN),
  FOREIGN KEY (tid) REFERENCES dimTime(tid)
);
```






# Loading Libraries

```{r warning=FALSE}
library(XML)
library(xslt)
```

# Load XML data to database

## Read XML file

```{r}
xmlPath <- "./pubmed_sample.xml"
xmlDoc = read_xml(xmlPath)
```

## Load dimJournal table

```{r}
xslPath = "./journal.xsl"
xslDoc = read_xml(xslPath,package="xslt")
journal_raw = xml_xslt(xmlDoc,xslDoc)
journals = unique(xmlToDataFrame(XML::xmlParse(journal_raw)))
dbWriteTable(DBcon,name = "dimJournal", value = journals, append = TRUE)
```

## Load Author table

```{r}
xslPath = "./author.xsl"
xslDoc = read_xml(xslPath,package="xslt")
author_raw = xml_xslt(xmlDoc,xslDoc)
authors = unique(xmlToDataFrame(XML::xmlParse(author_raw)))
authors = cbind(Author_id=rownames(authors),authors)
dbWriteTable(DBcon,name = "dimAuthor", value = authors, append = TRUE)
```

## Load articleFact

```{r}
xslPath = "./articleFact.xsl"
xslDoc = read_xml(xslPath,package="xslt")
author_raw = xml_xslt(xmlDoc,xslDoc)
authors = unique(xmlToDataFrame(XML::xmlParse(author_raw)))
authors = cbind(Author_id=rownames(authors),authors)
dbWriteTable(DBcon,name = "articleFact", value = authors, append = TRUE)
```
